services:
  svc-clash:
    image: registry.cn-hangzhou.aliyuncs.com/qpod/app-clash
    container_name: app-clash
    restart: unless-stopped
    volumes:
      - ./config.yaml:/opt/clash/config/config.yaml:ro
    ports:
      - "7890:7890"
      - "9090:9090"
    # When your system is Linux, you can use `network_mode: "host"` directly.
    # network_mode: "host"
