name: "${PROFILE_ENV:-X}-proxy-clash"

networks:
  net-proxy-clash:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  # Clash Transparent Proxy Gateway
  svc-proxy-clash:
    image: quay.io/labnow/clash:latest
    container_name: svc-clash
    hostname: svc-clash
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: Asia/Shanghai
      PROFILE_LOCALIZE: aliyun-pub
      PROXY_PROVIDER: https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
      NET_PROXY_SUBNET: 172.30.0.0/24

  # Example Application Container
  app-example:
    image: curlimages/curl:latest
    container_name: app-example
    networks:
      - net-proxy-clash
    dns:
      - 8.8.8.8
    depends_on:
      - svc-proxy-clash
    command: curl -fsSL https://ipinfo.io
