name: "svc-openclaw"

services:
  openclaw-gateway:
    container_name: svc-openclaw-gateway
    hostname: svc-openclaw-gateway
    image: "quay.io/labnow0dev/openclaw:latest"
    pull_policy: if_not_present
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - HOME=/home/node
      - TERM=xterm-256color
      - OPENCLAW_GATEWAY_BIND=${OPENCLAW_GATEWAY_BIND:-lan}
      - OPENCLAW_GATEWAY_PORT=${OPENCLAW_GATEWAY_PORT:-18789}
      - OPENCLAW_BRIDGE_PORT=${OPENCLAW_BRIDGE_PORT:-18790}
      - XDG_CONFIG_HOME=/opt/openclaw/data
    volumes:
      - /data/openclaw:/opt/openclaw/data
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    command:
      [
        "sh",
        "/usr/local/bin/start-openclaw.sh",
        "gateway",
        "--allow-unconfigured",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "${OPENCLAW_GATEWAY_PORT:-18789}"
      ]

  openclaw-cli:
    container_name: svc-openclaw-cli
    hostname: svc-openclaw-cli
    image: "quay.io/labnow0dev/openclaw:latest"
    pull_policy: if_not_present
    restart: "no"
    environment:
      - TZ=Asia/Shanghai
      - HOME=/home/node
      - TERM=xterm-256color
      - BROWSER=echo
      - XDG_CONFIG_HOME=/opt/openclaw/data
    volumes:
      - /data/openclaw:/opt/openclaw/data
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "openclaw.mjs"]
