#!/bin/sh
# vim:sw=2:ts=2:sts=2:et

set -eu

LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ME=$(basename "$0")
RESOLVERS_FILE=/etc/nginx/conf.d/include/resolvers.conf

entrypoint_log() {
    if [ -z "${NGINX_ENTRYPOINT_QUIET_LOGS:-}" ]; then
        echo "$@"
    fi
}

# 15-local-resolvers.envsh export NGINX_LOCAL_RESOLVERS (like "127.0.0.11 8.8.8.8")
# when NGINX_ENTRYPOINT_LOCAL_RESOLVERS is not set or empty, fallback to Docker's embedded DNS.
RESOLVERS="${NGINX_LOCAL_RESOLVERS:-127.0.0.11}"

mkdir -pv "$(dirname "$RESOLVERS_FILE")"

touch "$RESOLVERS_FILE" 2>/dev/null || {
    entrypoint_log "$ME: info: cannot write $RESOLVERS_FILE (read-only file system?)"
    exit 0
}

{
    echo "# Generated by $ME on $(date)"
    echo "resolver ${RESOLVERS} valid=10s ipv6=off;"
} > "$RESOLVERS_FILE"

entrypoint_log "$ME: wrote resolver ${RESOLVERS} to $RESOLVERS_FILE"
