services:
  db-postgres-casdoor:
      # su postgres && psql -d casdoor -U pg-casdoor-username
      image: docker.io/labnow/postgres-16:latest
      container_name: db-postgres
      environment:
        POSTGRES_DB: casdoor
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  svc-casdoor:
      image: docker.io/labnow/casdoor
      container_name: svc-casdoor
      # command: ["/bin/bash", "--login", "/opt/casdoor/server", "--createDatabase=true"]
      command: |
        /bin/bash -l -c '
        ls -alh /opt/casdoor
        echo "driverName = postgres" >> /opt/casdoor/conf/app.conf
        echo "dataSourceName = \"user=postgres password=postgres host=db-postgres port=5432 sslmode=disable dbname=casdoor\"" >> /opt/casdoor/conf/app.conf
        sleep 8s
        cat /opt/casdoor/conf/app.conf
        /opt/casdoor/server -createDatabase=true'
      ports:
        - 8000:8000
      depends_on:
        - db-postgres-casdoor
      healthcheck:
        test:  ["CMD-SHELL", "curl", "--head", "-fsSk", "https://localhost:8000/health/ready" ]
        interval: 30s
        timeout: 30s
        start_period: 5s
        retries: 3
