services:
  db-postgres:
  # su postgres && psql -d keycloak -U pg-keycloak-username
      image: docker.io/library/postgres:16
      container_name: db-postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: pg-keycloak-username
        POSTGRES_PASSWORD: pg-keycloak-password

  svc-keycloak:
      image: docker.io/labnow/keycloak
      # build:
      #   context: ../
      #   dockerfile: Dockerfile
      #   args:
      #     BASE_NAMESPACE: labnow0dev
      container_name: svc-keycloak
      # command: ["/bin/bash", "--login", "bin/kc.sh", "start-dev", "--verbose"]
      command: |
        /bin/bash -l -c '
          [ -f conf/server.keystore ] || keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 \
            -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
          bin/kc.sh start --verbose --features=token-exchange \
            --https-port=8080
          # --db postgres --db-url jdbc:postgresql://db-postgres:5432/keycloak \
          # --db-username pg-keycloak-username \
          # --db-password pg-keycloak-password
        '
      environment:
        KC_HOSTNAME: localhost
        KC_DB: postgres
        KC_DB_URL: "jdbc:postgresql://db-postgres:5432/keycloak"
        KC_DB_USERNAME: "pg-keycloak-username"
        KC_DB_PASSWORD: "pg-keycloak-password"
        KEYCLOAK_ADMIN: keycloak-admin
        KEYCLOAK_ADMIN_PASSWORD: keycloak-password
        PROXY_ADDRESS_FORWARDING: "true"
      ports:
        - 8080:8080
      depends_on:
        - db-postgres
      healthcheck:
        test:  ["CMD-SHELL", "curl", "--head", "-fsSk", "https://localhost:8080/health/ready" ]
        interval: 30s
        timeout: 30s
        start_period: 5s
        retries: 3

