#!/usr/bin/env bash
# Shared fail-closed helpers for P1 verification producers.  Never source .env.

verification_prepare_environment() {
  local env_file="$1" compose_file="$2" work_dir="$3"
  umask 077
  verification_environment_file="$work_dir/compose.environment"
  docker compose --env-file "$env_file" -f "$compose_file" config --environment > "$verification_environment_file"
  chmod 600 "$verification_environment_file"
}

verification_env() {
  local name="$1"
  awk -F= -v name="$name" '$1 == name {sub(/^[^=]*=/, ""); print; exit}' "$verification_environment_file"
}

verification_invalidate_report() {
  local report="$1"
  mkdir -p "$(dirname "$report")"
  chmod 700 "$(dirname "$report")"
  rm -f "$report"
}

verification_new_run_id() {
  python3 -c 'import secrets; print("p1-" + secrets.token_hex(16))'
}

verification_assert_run_id() {
  [[ "${VERIFICATION_RUN_ID:-}" =~ ^p1-[a-f0-9]{32}$ ]] || {
    echo "VERIFICATION_RUN_ID must be generated by verify-p1.sh" >&2
    return 2
  }
}
